# Generated by Django 4.1.5 on 2023-08-22 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='JobPost/default.svg', upload_to='JobPost/')),
                ('title', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('day', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('cooperation', models.CharField(default='تمام وقت', max_length=20)),
                ('city', models.CharField(default='تهران', max_length=50)),
                ('gender', models.CharField(default='مهم نیست', max_length=20)),
                ('category', models.CharField(default='هوش مصنوعی و داده', max_length=20)),
                ('salary', models.CharField(default='توافقی', max_length=20)),
                ('experience', models.CharField(default='مهم نیست', max_length=15)),
                ('creat_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('contact_email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='jobPost_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobPost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.jobpost')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.skills')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost_Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobPost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.jobpost')),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.options')),
            ],
        ),
        migrations.AddField(
            model_name='jobpost',
            name='options',
            field=models.ManyToManyField(to='website.options'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills',
            field=models.ManyToManyField(to='website.skills'),
        ),
    ]
