# Generated by Django 4.1.5 on 2023-08-22 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('surename', models.CharField(max_length=50)),
                ('number', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('birthdate', models.DateField(null=True)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.IntegerField(default=0)),
                ('university', models.CharField(max_length=255)),
                ('start_year', models.IntegerField(default=1351)),
                ('end_year', models.IntegerField(default=0)),
                ('Workplace', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('mager', models.CharField(max_length=255)),
                ('resume', models.FileField(upload_to='resume/')),
                ('location', models.CharField(choices=[('آذربایجان شرقی', 'آذربایجان شرقی'), ('آذربایجان غربی', 'آذربایجان غربی'), ('اردبیل', 'اردبیل'), ('اصفهان', 'اصفهان'), ('البرز', 'البرز'), ('ایلام', 'ایلام'), ('بوشهر', 'بوشهر'), ('تهران', 'تهران'), ('چهارمحال و بختیاری', 'چهارمحال و بختیاری'), ('خراسان جنوبی', 'خراسان جنوبی'), ('خراسان رضوی', 'خراسان رضوی'), ('خراسان شمالی', 'خراسان شمالی'), ('خوزستان', 'خوزستان'), ('زنجان', 'زنجان'), ('سمنان', 'سمنان'), ('سیستان و بلوچستان', 'سیستان و بلوچستان'), ('فارس', 'فارس'), ('قزوین', 'قزوین'), ('قم', 'قم'), ('کردستان', 'کردستان'), ('کرمان', 'کرمان'), ('کرمانشاه', 'کرمانشاه'), ('کهگیلویه و بویراحمد', 'کهگیلویه و بویراحمد'), ('گلستان', 'گلستان'), ('گیلان', 'گیلان'), ('لرستان', 'لرستان'), ('مازندران', 'مازندران'), ('مرکزی', 'مرکزی'), ('هرمزگان', 'هرمزگان'), ('همدان', 'همدان'), ('یزد', 'یزد')], default='تهران', max_length=50)),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], default='مرد', max_length=20)),
                ('marital_status', models.CharField(choices=[('مجرد', 'مجرد'), ('متاهل', 'متاهل')], default='مجرد', max_length=20)),
                ('degree', models.CharField(choices=[('دیپلم', 'دیپلم'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکترا', 'دکترا')], default='کارشناسی', max_length=20)),
                ('field', models.CharField(choices=[('هوش مصنوعی و داده', 'هوش مصنوعی و داده'), ('شبکه', 'شبکه'), ('امنیت', 'امنیت'), ('طراحی', 'طراحی'), ('برنامه نویسی و توسعه', 'برنامه نویسی و توسعه')], default='هوش مصنوعی و داده', max_length=20)),
                ('Favoritfield', models.CharField(choices=[('هوش مصنوعی و داده', 'هوش مصنوعی و داده'), ('شبکه', 'شبکه'), ('امنیت', 'امنیت'), ('طراحی', 'طراحی'), ('برنامه نویسی و توسعه', 'برنامه نویسی و توسعه')], default='هوش مصنوعی و داده', max_length=20)),
                ('abilities', models.ManyToManyField(to='website.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobseeker.resume')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.skills')),
            ],
        ),
    ]
